version: '3.8'
services:
  uponchart-postgresql:
    image: postgres:14.1
    # volumes:
    #   - ~/volumes/costardstudio/uponchart/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=uponchart
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5432:5432
